"""empty message

Revision ID: 79679f96f5bf
Revises: 
Create Date: 2025-05-11 00:21:30.674364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79679f96f5bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_classes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('total_classes')

    # ### end Alembic commands ###
